platform: 10.11.92.33

workspace:
  path: src/github.com/kubernetes-csi/external-snapshotter/v3

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    dns: 223.5.5.5
    pull: true

pipeline:

  gobuild:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go:1.15.2-buster
    dns: 223.5.5.5
    pull: true
    volumes:
      - /data/cache/golang/pkg/:/go/pkg/
    binary: csi-snapshotter
    main: cmd/csi-snapshotter

  docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    dns: 223.5.5.5
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dockerfile: .beagle/dockerfile
    base: registry.cn-qingdao.aliyuncs.com/wod/distroless-base:latest
    repo: wod/csi-snapshotter
    tag: v3.0.1
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:  
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master
